version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: MariaDB
    environment: 
      MYSQL_ROOT_PASSWORD:
        Friday13th!
      MYSQL_DATABASE:
        memestash
      MYSQL_USER:
        node_provider
      MYSSQL_PASSWORD:
        N0desslyExpress1ve
    ports: 
      - 3306:3306
  adminer:
    image: adminer
    container_name: DB-Interface
    restart: always
    ports:
      - 8080:8080
